name: KeepXP
version: ${project.version}
main: navy.warspite.keepxp.KeepXP
api-version: 1.13
authors: [warspite]
description: Keep XP
website: warspite.navy
permissions:
  KeepXP.*:
    children:
      KeepXP.da: true
  KeepXP.da:
    default: op